  cors:
    originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
  spring:
    application:
      name: restSpringboot
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/restspringboot?useTimezone=true&serverTimezone=UTC
      username: root
      password: Anglo2003@
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
      show-sql: false
      open-in-view: false
  logging:
    level:
      root: INFO
      #br.com.andreas: DEBUG
  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true

