  spring:
    application:
      name: restSpringboot
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/restspringboot?useTimezone=true&serverTimezone=UTC
      username: root
      password: Anglo2003@
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
      show-sql: false
      open-in-view: false
  logging:
    level:
      #root: WARN
      br.com.andreas: DEBUG
